"""add is_staff and name field to user model

Revision ID: 3f2f66453f36
Revises: e71e56798e9a
Create Date: 2023-04-12 11:58:13.081212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2f66453f36'
down_revision = 'e71e56798e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
